<?php
/**
 * Builds modules/Base/i/world-110m.svg, the realtime screen's country map.
 *
 * From Natural Earth's 1:110m admin-0 countries, which are public domain:
 *
 *   curl -LO https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_admin_0_countries.geojson
 *   php tests/tools/generate_world_map.php ne_110m_admin_0_countries.geojson
 *
 * One <g data-cc="XX"> per ISO 3166 alpha-2 code -- the code raw stores in
 * country_code -- holding that country's paths. The Equal Earth projection,
 * so a country's area on the map is its area on the ground and a shaded
 * country is not larger for being far north.
 *
 * BUNDLED, not fetched from a map service: a tile server would be sent the
 * address of everyone viewing the screen, and a self-hosted analytics
 * install should not report its users to a third party to draw a map.
 */

if ( $argc < 2 || ! is_readable( $argv[1] ) ) {

    fwrite( STDERR, "usage: php tests/tools/generate_world_map.php <ne_110m_admin_0_countries.geojson>\n" );
    exit( 2 );
}

const WIDTH = 1000;

/*
 * Natural Earth leaves these without an ISO code. MaxMind reports locations
 * there under the country each is recognised as part of, so that is the code
 * that has to shade them.
 */
const UNCODED = array( 'N. Cyprus' => 'CY', 'Somaliland' => 'SO' );

/** Equal Earth (Šavrič, Patterson, Jenny 2018), in projection units. */
function equal_earth( $lon, $lat ) {

    $a1 = 1.340264; $a2 = -0.081106; $a3 = 0.000893; $a4 = 0.003796;
    $m  = sqrt( 3 ) / 2;

    $lambda = deg2rad( $lon );
    $theta  = asin( $m * sin( deg2rad( $lat ) ) );
    $t2     = $theta * $theta;
    $t6     = $t2 * $t2 * $t2;

    $x = 2 * sqrt( 3 ) * $lambda * cos( $theta ) / ( 3 * ( 9 * $a4 * $t6 * $t2 + 7 * $a3 * $t6 + 3 * $a2 * $t2 + $a1 ) );
    $y = $theta * ( $a1 + $a2 * $t2 + $t6 * ( $a3 + $a4 * $t2 ) );

    return array( $x, $y );
}

list( $max_x ) = equal_earth( 180, 0 );
// The frame stops at 60S, where the southernmost land left (Tierra del Fuego,
// the South Sandwich Islands) ends; the far north is kept whole.
list( , $max_y ) = equal_earth( 0, 90 );
list( , $min_y ) = equal_earth( 0, -60 );

$scale  = WIDTH / ( 2 * $max_x );
$height = (int) ceil( ( $max_y - $min_y ) * $scale );

$point = function ( $lon, $lat ) use ( $scale, $max_x, $max_y ) {

    list( $x, $y ) = equal_earth( $lon, $lat );

    return array( round( ( $x + $max_x ) * $scale, 1 ), round( ( $max_y - $y ) * $scale, 1 ) );
};

/** One ring as path commands, dropping points that round onto the last. */
$ring = function ( array $coords ) use ( $point ) {

    $out  = '';
    $last = null;

    foreach ( $coords as $i => $c ) {

        $p = $point( $c[0], $c[1] );

        if ( $last !== null && abs( $p[0] - $last[0] ) < 0.6 && abs( $p[1] - $last[1] ) < 0.6 ) {

            continue;
        }

        $out  .= ( $last === null ? 'M' : 'L' ) . $p[0] . ' ' . $p[1];
        $last  = $p;
    }

    return $out . 'Z';
};

$geo = json_decode( (string) file_get_contents( $argv[1] ), true );

$groups = array();

foreach ( $geo['features'] as $feature ) {

    $props = $feature['properties'];
    $code  = $props['ISO_A2_EH'] ?? '-99';

    if ( $code === '-99' || $code === '' ) {

        $code = UNCODED[ $props['NAME'] ] ?? '';
    }

    // Antarctica is a fifth of the frame and no visitor's location.
    if ( $code === 'AQ' ) {

        continue;
    }

    if ( ! preg_match( '/^[A-Z]{2}$/', $code ) ) {

        fwrite( STDERR, sprintf( "skipped %s: no ISO code\n", $props['NAME'] ) );
        continue;
    }

    $geometry = $feature['geometry'];
    $polygons = $geometry['type'] === 'Polygon' ? array( $geometry['coordinates'] ) : $geometry['coordinates'];

    $d = '';

    foreach ( $polygons as $polygon ) {

        foreach ( $polygon as $coords ) {

            $d .= $ring( $coords );
        }
    }

    $groups[ $code ]['name']    = $groups[ $code ]['name'] ?? $props['NAME'];
    $groups[ $code ]['paths'][] = $d;
}

ksort( $groups );

$svg  = '<?xml version="1.0" encoding="UTF-8"?>' . "\n";
$svg .= '<!-- Generated by tests/tools/generate_world_map.php from Natural Earth 1:110m admin-0 countries (public domain). Equal Earth projection. -->' . "\n";
$svg .= sprintf( '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 %d %d">', WIDTH, $height ) . "\n";

foreach ( $groups as $code => $g ) {

    $svg .= sprintf( '<g data-cc="%s"><title>%s</title>', $code, htmlspecialchars( $g['name'], ENT_XML1 ) );

    foreach ( $g['paths'] as $d ) {

        $svg .= '<path d="' . $d . '"/>';
    }

    $svg .= "</g>\n";
}

$svg .= "</svg>\n";

$out = dirname( __DIR__, 2 ) . '/modules/Base/i/world-110m.svg';

file_put_contents( $out, $svg );

fprintf( STDOUT, "%s: %d countries, %d bytes\n", $out, count( $groups ), strlen( $svg ) );
