<?php
// GENERATED by the tracker build (webpack.config.js, TrackerVersionPlugin).
// Commit it with the change, like package-lock.json. The version goes up when
// anything the tracker is built from changes; an install recording a lower one
// has an update pending, which republishes its Profiles' bundles.
return array( 'version' => 1, 'sources' => '82751f17e6449699e87208eff01e53b6799b6b5a9e6b1658373c30698e8718d0' );
