jest.mock('jquery', () => {
    const jq = jest.requireActual('jquery');
    jq.__esModule = true;
    return jq;
});

import { OWA_instance as OWA } from '../../modules/Base/src/common/owa.js';
import { Util } from '../../modules/Base/src/common/Util.js';
import { OWATracker } from '../../modules/Base/src/tracker/Tracker.js';
import { CommandQueue } from '../../modules/Base/src/tracker/CommandQueue.js';

/**
 * Configurable cookie lifetimes, via the stateStoreExpirations option.
 *
 * The tracker used to decide on its own how long its cookies lived -- 364 days
 * for the visitor id, 60 for the campaign store, 364 for the session -- and
 * there was no way to reach those numbers from outside. A year-long identifier
 * is the first thing a "small privacy impact" argument loses on, so an operator
 * needs to be able to shorten it; the install-wide and per-Profile settings emit
 * this command into the snippet to do that.
 *
 * Three properties are worth pinning, and the third is the one that would
 * otherwise be true only by accident:
 *
 *   1. the command reaches the REGISTRY, which is the only thing persist()
 *      reads, so a changed lifetime is the lifetime actually written;
 *   2. an unknown store name does nothing, because the snippet is generated by
 *      a server that may be newer than the tracker on the page, and a thrown
 *      exception there is somebody else's site broken;
 *   3. the new lifetime is in place BEFORE the first cookie is written. The
 *      snippet pushes this ahead of trackPageView and the queue drains in push
 *      order -- so this holds today, and nothing but a test stops a later
 *      reordering from silently making the first page view of every visit write
 *      the old year.
 */

/** Capture cookie writes the way the tracker's persist path makes them. */
function captureCookies() {
    const written = [];

    jest.spyOn(Util, 'setCookie').mockImplementation((name, value, days) => {
        written.push({ name: name, value: value, days: days });
    });

    return written;
}

/**
 * The writes that STORE something, as opposed to the erasures.
 *
 * Util.deleteCookie() erases by setting the same name to an empty value with a
 * negative age, and the tracker does erase cookies on the cookie-domain path. An
 * expiration assertion has to skip those: -1 there is the erasure saying "now",
 * not a lifetime anybody configured.
 */
function persistedWrites(cookies, name) {

    return cookies.filter((c) => c.name === name && c.value !== '');
}

function reset() {
    OWA.initializeStateManager();
    OWA.state.stores = {};
    OWA.state.storeFormats = {};
    OWA.state.storeMeta = {};
    OWA.state.hydrated = {};
    OWA.state.persistenceReleased = {};
}

beforeEach(() => {
    reset();
    OWA.setSetting('ns', 'owa_');
    OWA.setSetting('cookie_domain', 'example.com');
});

afterEach(() => {
    jest.restoreAllMocks();
    reset();
    delete window.owa_baseUrl;
    delete window.OWATracker;
});

describe('the configured lifetime is what the registry answers with', () => {

    test('a configured visitor lifetime replaces the registered one', () => {

        const tracker = new OWATracker({ cookie_domain_set: true, site_id: 'exp-site' });

        expect(OWA.state.getExpirationDays('v')).toBe(364);

        tracker.setOption('stateStoreExpirations', { v: 90 });

        expect(OWA.state.getExpirationDays('v')).toBe(90);
    });

    /*
     * The campaign-store case was here. There is no 'c' store any more: it held
     * the client's attribution stack, which the server never read, and it went
     * with the attribution models. The cases around this still cover that
     * naming one store does not disturb another.
     */

    /**
     * The session store is per site -- it is registered as 's_<siteId>'. The
     * snippet names it 's', because the server writing the snippet does not know
     * which tracker object will receive the command, so the tracker is what has
     * to resolve it. Getting this wrong is invisible: 's' would be "unregistered"
     * and quietly ignored, and the session cookie would keep the old lifetime.
     */
    test("the session lifetime lands on this tracker's per-site store", () => {

        const tracker = new OWATracker({ cookie_domain_set: true, site_id: 'exp-site' });

        tracker.setOption('stateStoreExpirations', { s: 30 });

        expect(OWA.state.getExpirationDays('s_exp-site')).toBe(30);
    });

    test('a store name the tracker does not know is ignored, not thrown on', () => {

        const tracker = new OWATracker({ cookie_domain_set: true, site_id: 'exp-site' });

        expect(() => tracker.setOption('stateStoreExpirations', { nosuchstore: 90 })).not.toThrow();
        expect(OWA.state.getExpirationDays('nosuchstore')).toBeUndefined();
        // and it must not have registered the store as a side effect
        expect(OWA.state.storeMeta.hasOwnProperty('nosuchstore')).toBe(false);
    });

    test('a valid entry still applies when it shares the map with an unknown one', () => {

        const tracker = new OWATracker({ cookie_domain_set: true, site_id: 'exp-site' });

        tracker.setOption('stateStoreExpirations', { nosuchstore: 90, v: 45 });

        expect(OWA.state.getExpirationDays('v')).toBe(45);
    });

    test.each([
        ['zero', 0],
        ['negative', -30],
        ['fractional', 90.5],
        ['not a number', 'ninety'],
        ['empty', ''],
        ['null', null],
    ])('a %s value is ignored rather than coerced', (_label, value) => {

        const tracker = new OWATracker({ cookie_domain_set: true, site_id: 'exp-site' });

        tracker.setOption('stateStoreExpirations', { v: value });

        expect(OWA.state.getExpirationDays('v')).toBe(364);
    });

    test('a numeric string is accepted, because JSON is not the only source', () => {

        const tracker = new OWATracker({ cookie_domain_set: true, site_id: 'exp-site' });

        tracker.setOption('stateStoreExpirations', { v: '90' });

        expect(OWA.state.getExpirationDays('v')).toBe(90);
    });

    test('no map at all does nothing', () => {

        const tracker = new OWATracker({ cookie_domain_set: true, site_id: 'exp-site' });

        expect(() => tracker.setOption('stateStoreExpirations')).not.toThrow();
        expect(OWA.state.getExpirationDays('v')).toBe(364);
    });

    /**
     * setSiteId() re-runs registerSiteScopedStores(), which re-registers the
     * session store with the shipped 364. A configured lifetime has to survive
     * that, or reconfiguring a tracker silently restores the year.
     */
    test('a configured session lifetime survives a change of site id', () => {

        const tracker = new OWATracker({ cookie_domain_set: true, site_id: 'exp-site' });

        tracker.setOption('stateStoreExpirations', { s: 30 });
        tracker.setSiteId('other-site');

        expect(OWA.state.getExpirationDays('s_other-site')).toBe(30);
    });
});

describe('the configured lifetime is what actually gets written', () => {

    test('persisting the visitor store uses the configured expiration', () => {

        const cookies = captureCookies();
        const tracker = new OWATracker({ cookie_domain_set: true, site_id: 'exp-site' });

        tracker.setOption('stateStoreExpirations', { v: 90 });

        OWA.setState('v', 'visitor_id', '123', true);
        OWA.state.persist('v', true);

        const owa_v = cookies.filter((c) => c.name === 'owa_v');

        expect(owa_v.length).toBeGreaterThan(0);
        expect(owa_v[owa_v.length - 1].days).toBe(90);
    });
});

/**
 * The ordering guarantee, driven through the real command queue rather than by
 * calling the methods in a convenient order.
 *
 * This is the whole reason the snippet puts the option ahead of
 * trackPageView. CommandQueue.process() shifts the array and dispatches in push
 * order, so by the time trackPageView causes the first persist the registry has
 * already been changed. A test that called the two methods directly would prove
 * nothing about that -- it would just be asserting the order it itself chose.
 */
describe('the expiration is in place before the first cookie is written', () => {

    beforeEach(() => {
        window.owa_baseUrl = 'https://owa.example.test/';
        // The queue builds the tracker itself, without the cookie_domain_set
        // escape hatch, so it runs the real lazy setCookieDomain() path --
        // which reads document.domain, undefined in jsdom.
        Object.defineProperty(document, 'domain', {
            configurable: true,
            get() { return 'site.example'; },
        });
    });

    test('a visitor cookie written by the first trackPageView carries the configured lifetime', () => {

        const cookies = captureCookies();
        // The beacon is `new Image(1,1); image.src = url`; swallow it.
        const OrigImage = global.Image;
        global.Image = class { set src(v) {} };

        try {
            const q = new CommandQueue();

            // Exactly what js_log_tag.php emits, in the order it emits it.
            q.loadCmds([
                ['setSiteId', 'exp-site'],
                ['setOption', 'stateStoreExpirations', { v: 90, s: 30 }],
                ['trackPageView'],
            ]);
            q.process();

            const owa_v = persistedWrites(cookies, 'owa_v');

            expect(owa_v.length).toBeGreaterThan(0);
            // Every write, not merely the last one: the point is that NO cookie
            // was ever written with the old lifetime, not that the final state
            // happens to be right.
            owa_v.forEach((c) => expect(c.days).toBe(90));
        } finally {
            global.Image = OrigImage;
        }
    });

    test('the same snippet with no expiration command still writes the shipped default', () => {

        const cookies = captureCookies();
        const OrigImage = global.Image;
        global.Image = class { set src(v) {} };

        try {
            const q = new CommandQueue();

            q.loadCmds([
                ['setSiteId', 'exp-site'],
                ['trackPageView'],
            ]);
            q.process();

            const owa_v = persistedWrites(cookies, 'owa_v');

            expect(owa_v.length).toBeGreaterThan(0);
            owa_v.forEach((c) => expect(c.days).toBe(364));
        } finally {
            global.Image = OrigImage;
        }
    });
});
